version: '3.8'

networks:
  dev:

services:
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile  # This should be the Dockerfile that builds your frontend app
      networks:
        - dev
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Ensure you're referencing the Dockerfile that sets up Nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SESSION_ENCRYPTION_KEY=${SESSION_ENCRYPTION_KEY}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  

volumes:
  postgres_data:
